## 一、导入标准库

In [1]:
# python3
# Importing the libraries 导入库
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# 使图像能够调整
%matplotlib notebook 
#中文字体显示  
plt.rc('font', family='SimHei', size=8)

## 二、导入数据

In [3]:
dataset = pd.read_csv('./Churn_Modelling.csv') # 通过已知的顾客信息来预测顾客是否留在这个银行
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [17]:
X = dataset.iloc[:, 3:13].values # 影响顾客是否去留的因素
y = dataset.iloc[:, 13].values     # 顾客去留
X,y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ..., 
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0], dtype=int64))

## 三、虚拟变量处理

In [18]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1= LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1]) # 将国家变为数字


In [19]:
labelencoder_X_2= LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2]) # 将性别变为数字
onehotencoder = OneHotEncoder(categorical_features = [1])# 将国家变为虚拟变量（避免三个值有前后顺序）
X = onehotencoder.fit_transform(X).toarray()    
X = X[:,1:] # 删去第0列，避免虚拟变量陷阱
X

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.02000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   7.09000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  1.00000000e+00,   0.00000000e+00,   7.72000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   7.92000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

## 四、区分训练集和测试集

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 0)

## 五、创建神经网络

In [21]:
# 导入标准库
import keras
from keras.models import Sequential
from keras.layers import Dense

## 六、ANN

In [36]:
classifier = Sequential()
# 隐藏层 RELU（线性整流函数），输出层用S函数 

# 添加第一个隐藏层
classifier.add(Dense(units=6 ,activation='relu' ,kernel_initializer='uniform' ,input_dim = 11))  # 输入11个变量，输出1、所以隐藏层设置输入+输出/2,所以设置为6

# 添加第二个隐藏层
classifier.add(Dense(units=6 ,activation='relu' ,kernel_initializer='uniform' ))  # 输入11个变量，输出1、所以隐藏层设置输入+输出/2,所以设置为6

# 输出层
classifier.add(Dense(units=1 ,activation='sigmoid' ,kernel_initializer='uniform' ))   # 输出大于1个时，kernel_initializer 为softmax

# 编译
classifier.compile(optimizer= 'adam',loss= 'binary_crossentropy' , metrics=['accuracy']) # 分类结果2个binary_crossentropy,3个及其以上categorial_crossentropy

# 拟合
classifier.fit(X_train,y_train, batch_size= 10, epochs= 100)

Epoch 1/100
8000/8000 [==============================] - 60s 8ms/step - loss: 0.5448 - acc: 0.7927
Epoch 2/100
8000/8000 [==============================] - 54s 7ms/step - loss: 0.5227 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 54s 7ms/step - loss: 0.5118 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 38s 5ms/step - loss: 0.5085 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 36s 4ms/step - loss: 0.5058 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 50s 6ms/step - loss: 0.5034 - acc: 0.7960:  - ETA: 12s - loss: 0.5041 - ETA: 11s -  - ETA: 10s - loss: 0. - ETA: 8s - loss: 0.5051 - - ETA: 7s - loss: 0.5060 - acc: 0.7 - ETA: 7s - ETA: - ETA - ETA: 0s - loss: 0.5036 - 
Epoch 7/100
8000/8000 [==============================] - 55s 7ms/step - loss: 0.5047 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 57s 7ms/step - loss: 0.5023 - acc: 0.7960A: 9s - l - ETA: 7s - loss: 0.5

8000/8000 [==============================] - 57s 7ms/step - loss: 0.4985 - acc: 0.7960: 10s - loss: 0.5001 - ETA: 10s -
Epoch 71/100
8000/8000 [==============================] - 54s 7ms/step - loss: 0.4995 - acc: 0.7960: 3s - loss: 0.5006 - - ETA: 2s - loss:  - ETA: 1s - loss: 0
Epoch 72/100
8000/8000 [==============================] - 55s 7ms/step - loss: 0.4989 - acc: 0.7960
Epoch 73/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4991 - acc: 0.7959  E - ETA: 10s - loss: 0.5004 - acc: 0. - ETA: 10s - loss:  - ETA: 9s - loss: 0.5019 - a - ETA: 8s - loss: 0.5035 - a - 56s 7ms/step - loss: 0.4989 - acc: 0.7960
Epoch 74/100
8000/8000 [==============================] - 50s 6ms/step - loss: 0.5010 - acc: 0.7960: 0s - loss: 0.5010 - acc: 0.79
Epoch 75/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4992 - acc: 0.7962- ETA: 4s - loss: 0.5021 - acc - ETA: 4s - loss: 0.5014 - ac - ETA - ETA: 1s - lo - 52s 7ms/step - loss: 0.4995 - acc: 0.7960
Epoch 76/100


## 七、预测测试集的结果

In [43]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

## 八、混淆矩阵

In [44]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[1595,    0],
       [ 405,    0]], dtype=int64)

## 九、项目地址

### https://coding.net/u/RuoYun/p/Python-of-machine-learning/git/blob/master/00%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/5.%E8%BF%9B%E9%98%B6%E7%AE%97%E6%B3%95/2.%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/1.%E4%BA%BA%E5%B7%A5%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C/0.txt?public=true